site_name: Wiki Monstra
site_url: https://localhost

plugins:
  - search

theme:
  language: pt-BR
  logo: assets/icon_70.png
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: blue grey

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue grey

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black

  features:
    - toc.follow
    - navigation.expand
    - navigation.tabs
    - navigation.instant
    - naigation.indexes
    - navigation.instant.progress
    - navigation.tracking

    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Onboarding: onboarding/intro.md
  - Politicas: politicas/intro.md
  - Manuais: manual/intro.md
  - Metodos: metodos/intro.md
  - Wiki: database/intro.md
