# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Wiki Monstra
site_url: https://localhost

plugins:
  - mkdocs-audio
  - search

theme:
  language: pt-BR
  logo: assets/icon_70.png
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: blue grey

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue grey

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black

  features:
    - toc.follow
    # Navigation <---------------------
    - navigation.expand
    - navigation.tabs
    - navigation.instant
    - naigation.indexes
    - navigation.instant.progress
    - navigation.tracking
    # -------------------------------->

    # Search <----------------
    - search.suggest
    - search.highlight
    - search.share
    # -------------------------------->

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: 
    - Intro: index.md
